### ISSUE TITLE
The URL of the website for repository details is wrong.

### ISSUE THREAD

**Issue by hiro0218** [htmlplus/core#37]
The URL listed in this repository is incorrect.

Isn't the correct one as follows?

```diff
-https://htmplus.io/
+https://htmlplus.io/
```

<img width="300" alt="image" src="https://user-images.githubusercontent.com/3617124/120897294-4ca56580-c660-11eb-8d04-13d62c2ec08d.png">

**Comment by amirtvkli** [comment]
Hi @hiro0218,
Thanks. It's resolved. 
closes #37
